package com.app.modules.notifications.entity;

public enum NotificationType {
    CONGE_SOUMIS,
    CONGE_VALIDE,
    CONGE_REJETE,
    FACTURE_EN_RETARD,
    DOCUMENT_EXPIRE_BIENTOT,
    BUDGET_ALERTE_80PCT,
    CONTRAT_EXPIRE_BIENTOT,
    ECHEANCE_FIN_CDD,
    ECHEANCE_FIN_PERIODE_ESSAI,
    ECHEANCE_VISITE_MEDICALE,
    ECHEANCE_TITRE_SEJOUR,
    ECHEANCE_FORMATION_OBLIGATOIRE,
    ECHEANCE_AVENANT_CONTRAT,
    ECHEANCE_AUTRE,
    BIEN_MAINTENANCE,
    SALAIRE_DU
}

